// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareAGame.DataAccess;

namespace ShareAGame.DataAccess.Migrations
{
    [DbContext(typeof(ShareAGameContext))]
    [Migration("20220425131020_AddedGameEntity")]
    partial class AddedGameEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareAGame.DataAccess.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDigital")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("277eb80b-5574-4728-bdaa-63d25c6847a1"),
                            IsDigital = true,
                            Name = "Lara Croft Tomb Raider"
                        },
                        new
                        {
                            Id = new Guid("e971fe57-1b27-46d9-9822-88d63b0caa76"),
                            IsDigital = true,
                            Name = "Assasin Creed Valhalla"
                        },
                        new
                        {
                            Id = new Guid("2ef01f75-7eee-4838-af26-bfb4cf2d0e06"),
                            IsDigital = false,
                            Name = "Watch Dogs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
