// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareAGame.DataAccess;

namespace ShareAGame.DataAccess.Migrations
{
    [DbContext(typeof(ShareAGameContext))]
    partial class ShareAGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareAGame.DataAccess.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDigital")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c25768ec-aa28-4e8c-bde2-715d45efac0f"),
                            IsDigital = true,
                            Name = "Lara Croft Tomb Raider"
                        },
                        new
                        {
                            Id = new Guid("cb606a24-9426-4d44-808c-dfebb3da7900"),
                            IsDigital = true,
                            Name = "Assasin Creed Valhalla"
                        },
                        new
                        {
                            Id = new Guid("ff9cde62-805e-4538-8fe9-8d7372cc31c2"),
                            IsDigital = false,
                            Name = "Watch Dogs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
